### ISSUE TITLE
How to obtain the cam_extrinsics and  cam_intrinsics in habitat?

### ISSUE THREAD

**Issue by daiguangzhao** [XiaohanLei/GaussNav#2]
雷师兄您好，谢谢您和您的团队给社区带来如如此优秀的工作。想问您，是如何在habitat坐标系中获得的相机的内参和外参？我在自己的VLN-CE项目中，想要用3DGS的技术栈做一些渲染工作，但是我一直无法获得正确的相机内外参。

我做了以下准备：我试着直接用机器人rotation改写成旋转矩阵R，但是训练视觉和GT视角对不上。此外，
![1727073598925](https://github.com/user-attachments/assets/75ec7766-72e9-422a-9725-60e95d98bcc7)
在我的印象中，habitat默认的坐标系是围绕Y轴旋转的，而且坐标系并不是标准的笛卡尔坐标系。于是，我把相机的position原始的y轴和z轴坐标互换，且在更换后的轴加了负号。

**Comment by daiguangzhao** [comment]
当我固定上述代码的angel为math.pi/2做一个训练可视化，但却出现了错误。在我出现GS的过程中，出现了以下的训练可视化结果，其中左边是GT（红色标记），右边是GS训练出来的。从结果可以看到有些视角是可以正常拟合的，有些视角的渲染却完全对不上。
![1727073714381](https://github.com/user-attachments/assets/30d60f02-54c3-441e-8ed1-fdbc51c8ba1e)

**Comment by XiaohanLei** [comment]
### question：是如何在habitat坐标系中获得的相机的内参和外参

#### 内参
对于内参，habitat中都是simple pinhole camera且没有畸变，你可以直接通过h,w和fov算出来
#### 外参
可以参考一下habitat的相机坐标系规范https://aihabitat.org/docs/habitat-sim/coordinate-frame-tutorial.html
在一些nerf中从habitat读到的camera 2 world matrix是可以直接用的，但是gs使用的还是colmap坐标系，所以y和z轴需要flip，habitat中读取c2w代码可以参考
```
    def get_transformation_matrix(self):

        current_position = self._env.sim.get_agent_state(0).position
        current_rotation = self._env.sim.get_agent_state(0).rotation

        # Convert the rotation quaternion to a rotation matrix
        current_rotation_matrix = quaternion.as_rotation_matrix(current_rotation)

        current_transform = np.eye(4)
        current_transform[:3, :3] = current_rotation_matrix
        current_transform[:3, 3] = current_position

        return current_transform
```

**Comment by daiguangzhao** [comment]
> ### question：是如何在habitat坐标系中获得的相机的内参和外参
> #### 内参
> 对于内参，habitat中都是simple pinhole camera且没有畸变，你可以直接通过h,w和fov算出来
> 
> #### 外参
> 可以参考一下habitat的相机坐标系规范https://aihabitat.org/docs/habitat-sim/coordinate-frame-tutorial.html 在一些nerf中从habitat读到的camera 2 world matrix是可以直接用的，但是gs使用的还是colmap坐标系，所以y和z轴需要flip，habitat中读取c2w代码可以参考
> 
> ```
>     def get_transformation_matrix(self):
> 
>         current_position = self._env.sim.get_agent_state(0).position
>         current_rotation = self._env.sim.get_agent_state(0).rotation
> 
>         # Convert the rotation quaternion to a rotation matrix
>         current_rotation_matrix = quaternion.as_rotation_matrix(current_rotation)
> 
>         current_transform = np.eye(4)
>         current_transform[:3, :3] = current_rotation_matrix
>         current_transform[:3, 3] = current_position
> 
>         return current_transform
> ```
谢谢师兄回复，按照你的修改建议，我对我的RT重新进行修改，视角依然是无法对齐。麻烦您帮我看下这部分代码，是否出现了其他的问题。
![1727092990217](https://github.com/user-attachments/assets/c8b87331-278c-45c3-8e24-c3fcd54a5123)

**Comment by XiaohanLei** [comment]
建议可以试试这几行代码
```
P = np.array([
                [1, 0, 0, 0],
                [0, -1, 0, 0],
                [0, 0, -1, 0],
                [0, 0, 0, 1]
            ])
new_c2w = P @ c2w @ P.T
```
其中c2w是从habitat中读到的transformation matrix，new_c2w是要送到GS中的

**Comment by JiahuaPei** [comment]
```
def get_camera_intrinsics(sim, sensor_name):
    # Get render camera
    render_camera = sim._sensors[sensor_name]._sensor_object.render_camera

    # Get projection matrix
    projection_matrix = render_camera.projection_matrix

    # Get resolution
    viewport_size = render_camera.viewport

    # Intrinsic calculation
    fx = projection_matrix[0, 0] * viewport_size[0] / 2.0
    fy = projection_matrix[1, 1] * viewport_size[1] / 2.0
    cx = (projection_matrix[2, 0] + 1.0) * viewport_size[0] / 2.0
    cy = (projection_matrix[2, 1] + 1.0) * viewport_size[1] / 2.0

    intrinsics = np.array([
        [fx, 0, cx],
        [0, fy, cy],
        [0,  0,  1]
    ])
    return intrinsics
print(get_camera_intrinsics(sim, 'color_sensor'))
# print(get_camera_intrinsics(sim, 'depth_sensor'))
```
